{% set name = "rsatoolbox" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rsatoolbox-{{ version }}.tar.gz
  sha256: 2d091cbaa33373bf9da4df5ca8d127f0e427431a3db726076090ab2d54fe1213

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - scipy
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python
    - {{ pin_compatible('scipy') }}
    - numpy
    - pandas
    - scikit-learn
    - scikit-image
    - matplotlib-base
    - h5py
    - joblib
    - tqdm

test:
  imports:
    - rsatoolbox
  commands:
    - pip check
    - python -m unittest -v rsatoolbox.test
  requires:
    - pip

about:
  home: https://github.com/rsagroup/rsatoolbox
  summary: Representational Similarity Analysis (RSA) in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://rsatoolbox.readthedocs.io/
  dev_url: https://github.com/rsagroup/rsatoolbox

extra:
  recipe-maintainers:
    - ilogue
