{% set name = "rsatoolbox" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rsatoolbox-{{ version }}.tar.gz
  sha256: 5aa97b3330ecf181dbe7b8e3661bdcf92d9bb0dcc129d0c366433f7d8aae7663

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - scipy
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python
    - {{ pin_compatible('scipy') }}
    - numpy
    - pandas
    - scikit-learn
    - scikit-image
    - matplotlib-base !=3.9.1
    - h5py
    - joblib
    - tqdm
    - networkx
    - importlib_resources  # [py<39]

test:
  imports:
    - rsatoolbox
  commands:
    - pip check
    - python -m unittest -v rsatoolbox.test
  requires:
    - pip

about:
  home: https://github.com/rsagroup/rsatoolbox
  summary: Representational Similarity Analysis (RSA)
  description: Representational Similarity Analysis (RSA)
  license: MIT
  license_file: LICENSE
  doc_url: https://rsatoolbox.readthedocs.io/
  dev_url: https://github.com/rsagroup/rsatoolbox

extra:
  recipe-maintainers:
    - JasperVanDenBosch
