{% set name = "rsatoolbox" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rsatoolbox-{{ version }}.tar.gz
  sha256: ecdcb50387c4b6330077ec2a3a221696078071319b8a0c32ed8128cd38da6863

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - scipy
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python
    - {{ pin_compatible('scipy') }}
    - numpy
    - pandas
    - scikit-learn
    - scikit-image
    - matplotlib-base
    - h5py
    - joblib
    - tqdm
    - networkx
    - importlib_resources >=5.12;python_version<"3.9"

test:
  imports:
    - rsatoolbox
  commands:
    - pip check
    - python -m unittest -v rsatoolbox.test
  requires:
    - pip

about:
  home: https://github.com/rsagroup/rsatoolbox
  summary: Representational Similarity Analysis (RSA)
  description: Representational Similarity Analysis (RSA)
  license: MIT
  license_file: LICENSE
  doc_url: https://rsatoolbox.readthedocs.io/
  dev_url: https://github.com/rsagroup/rsatoolbox

extra:
  recipe-maintainers:
    - JasperVanDenBosch
